name: Build DEB for PRs

on:
  pull_request:
    branches:
    - main

jobs:
  pre_job:
    name: Path match check
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ github.token }}
  latest_kolibri_release:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    outputs:
      tar-url: ${{ steps.get_latest_kolibri_release.outputs.result }}
    steps:
      - name: Get latest Kolibri release
        id: get_latest_kolibri_release
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |

            const { data: releases } = await github.rest.repos.listReleases({
              owner: 'learningequality',
              repo: 'kolibri',
              per_page: 1,
              page: 1,
            });

            const latestRelease = releases[0];
            const tarAsset = latestRelease.assets.find(asset => asset.name.endsWith('.tar.gz'));
            const tarUrl = tarAsset.browser_download_url;
            return tarUrl;

  build_deb:
    name: Build DEB file
    needs: [pre_job, latest_kolibri_release]
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    uses: ./.github/workflows/build_deb.yml
    with:
      tar-url: ${{ needs.latest_kolibri_release.outputs.tar-url }}
